### PR TITLE
Feature/ios present-proof

### PR DESCRIPTION
**Pull request by JamesKEbert**
Adds support for present-proof in iOS.
Fixed schema parsing in iOS.
Adds deprecation notice on relevant functions and corresponding method creation todos (as noted in indy-sdk).
Moves Java Presentation Search methods to Anoncreds' section.

Still need to add verify proof in iOS, but ended up needing to do that as a separate PR.

### CODE REVIEW

**Comment by icc-romeu** [comment]
👏Nice one @JamesKEbert ! I see there is still work to be done. May I help you there?

**Review by TimoGlastra — APPROVED** [review]
Nice!

**Comment by jakubkoci** [comment]
Thanks @JamesKEbert 👍

**Comment by JamesKEbert** [comment]
For sure!
@icc-romeu I would definitely not be opposed to help there. The only thing left really was to alter the verifierVerifyProof() method to also work in iOS, which I don't think is a significant lift. I just didn't have the app environment I was working in set up yesterday to really test the functionality.

**Pull request merged**
