### PR TITLE
Adds some missing methods for prover

### PR DESCRIPTION
**Pull request by abdelghafour**

### CODE REVIEW

**Comment by jakubkoci** [comment]
Thanks @abdelghafour for the contribution. I just want to ask you to put your JS methods into `src/index.js` file and not into `lib/index.js`, please.  You don't have to run any `build` command for these changes. The build step and `lib/index.js` file are used just for the distribution as NPM package.

**Comment by abdelghafour** [comment]
Hello @jakubkoci, yeah of course, we have done in a rush to distribute it amongst our team, we needed to have these fixes to continue our work :). Once finalized, we will remove WIP.
Cheers.

**Comment by jakubkoci** [comment]
OK, I see. One more thing... I also added code format check command and pre-push hook with my last commit. You can run `npm run format` or `yarn format` to format the code and pass this validation before you push your changes.

**Comment by abdelghafour** [comment]
Hello, @jakubkoci please take a look at https://github.com/Taillis-Labs/rn-indy-sdk/wiki/Simple-working-prototype-of-rn-indy-sdk
Thank you.

**Comment by jakubkoci** [comment]
> Hello, @jakubkoci please take a look at https://github.com/Taillis-Labs/rn-indy-sdk/wiki/Simple-working-prototype-of-rn-indy-sdk
> Thank you.

Sorry @abdelghafour what exactly should I look at? I see an empty wiki page at the given link. But I've merged your changes if that was your suggestion :)

**Comment by abdelghafour** [comment]
hello @jakubkoci, our team has attached a simple working prototype (node + RN) here: https://github.com/Taillis-Labs/rn-indy-sdk/wiki/Simple-working-prototype-of-rn-indy-sdk, we received some questions/blockers about how to use the wrapper in RN, so we created that small wiki as guideline for implementation

**Pull request merged**
